characters_file = open('meus-personagens.txt', mode="w")

characters_file.write("Darth Vader\n")
characters_file.write("Luke Skywalker\n")
characters_file.write("Han Solo\n")
characters_file.write("Leia Organa\n")
characters_file.write("Chewbacca\n")
characters_file.write("R2-D2\n")
characters_file.write("C-3PO\n")
characters_file.write("Boba Fett\n")
characters_file.write("Lando Calrissian\n")
characters_file.write("Jabba the Hutt\n")
characters_file.write("Wedge Antilles\n")
characters_file.write("Yoda\n")
characters_file.write("Palpatine\n")
characters_file.write("Obi-Wan Kenobi\n")
characters_file.write("Qui-Gon Jinn\n")
characters_file.write("Padmé Amidala\n")
characters_file.write("Mace Windu\n")
characters_file.write("Darth Maul\n")
characters_file.write("Jango Fett\n")
characters_file.write("Count Dooku\n")
characters_file.write("General Grievous\n")
characters_file.write("Jar Jar Binks\n")
characters_file.write("Watto\n")
characters_file.write("Nute Gunray\n")
characters_file.write("Boss Nass\n")
characters_file.write("Sebulba\n")
characters_file.write("Shmi Skywalker\n")
characters_file.write("Darth Plagueis\n")
characters_file.write("Jocasta Nu\n")
characters_file.write("Ki-Adi-Mundi\n")
characters_file.write("Kit Fisto\n")
characters_file.write("Plo Koon\n")
characters_file.write("Aayla Secura\n")
characters_file.write("Dexter Jettster\n")
characters_file.write("Lama Su\n")
characters_file.write("Taun We\n")
characters_file.write("Wat Tambor\n")
characters_file.write("San Hill\n")
characters_file.write("Shaak Ti\n")
characters_file.write("Grievous\n")
characters_file.write("Tarfful\n")
characters_file.write("Raymus Antilles\n")
characters_file.write("Sly Moore\n")
characters_file.write("Tion Medon\n")
characters_file.write("Finn\n")
characters_file.write("Rey\n")
characters_file.write("Poe Dameron\n")
characters_file.write("Kylo Ren\n")
characters_file.write("Maz Kanata\n")
characters_file.write("Supreme Leader Snoke\n")
characters_file.write("General Hux\n")
characters_file.write("Captain Phasma\n")
characters_file.write("BB-8\n")
characters_file.write("R2-D2\n")
characters_file.write("C-3PO\n")
characters_file.write("Chewbacca\n")
characters_file.write("Lor San Tekka\n")
characters_file.write("Unkar Plutt\n")
characters_file.write("Sidon Ithano\n")
characters_file.write("Bala-Tik\n")
characters_file.write("Ello Asty\n")
characters_file.write("Jessika Pava\n")
print("Arquivo criado com sucesso!")
characters_file.close()